# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd757e3d8da16fae18387df1cf5544ad442e32d340a308d4ddb088dfedb91449732df122906d1dfb1e64e1788ad7b5f0bc69281401958690f9a579d23683dad

test:
  secret_key_base: ef03131893146707e59b6d7602e8eedf747faccb18d33d0b95de8d687b94bb4455a6c9de669413a59bc3aaa21075fbfc1f0e0a12908824dfc2183653e7b3ca60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
